# Generated by Django 2.0.2 on 2018-03-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RollStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('paperType', models.CharField(max_length=264, unique=True)),
                ('lineal', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=264, unique=True)),
                ('lastname', models.CharField(max_length=264, unique=True)),
                ('email', models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
