# Generated by Django 2.0.2 on 2018-04-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_coordinates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
